/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DrawImport } from './routes/draw'
import { Route as DecksImport } from './routes/decks'
import { Route as CollectionImport } from './routes/collection'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DrawRoute = DrawImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRoute,
} as any)

const DecksRoute = DecksImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRoute,
} as any)

const CollectionRoute = CollectionImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionImport
      parentRoute: typeof rootRoute
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksImport
      parentRoute: typeof rootRoute
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRoute
  '/draw': typeof DrawRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRoute
  '/draw': typeof DrawRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRoute
  '/draw': typeof DrawRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collection' | '/decks' | '/draw'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collection' | '/decks' | '/draw'
  id: '__root__' | '/' | '/collection' | '/decks' | '/draw'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  DecksRoute: typeof DecksRoute
  DrawRoute: typeof DrawRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  DecksRoute: DecksRoute,
  DrawRoute: DrawRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/collection",
        "/decks",
        "/draw"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/collection": {
      "filePath": "collection.tsx"
    },
    "/decks": {
      "filePath": "decks.tsx"
    },
    "/draw": {
      "filePath": "draw.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
